### ISSUE TITLE
smtp on HestiaCP not worked

### ISSUE THREAD

**Issue by TOWUK** [pachno/pachno#10] opened 2021-06-24 18:41 UTC
i create account mail on my domain and use smtp on pachno. smtp sent and dont delivery...

**Comment by mzch** [comment] 2021-09-01 15:28
I tried to set up my SMTP server, but I was unable to select `CONNECTION ENCRYPTION`.
`Use SSL encryption` and `Use TLS encryption` options are gray-outed.
So Pachno failed to send mails.

**Comment by jagansankara** [comment] 2021-11-21 19:06
Any update on this bug. Because of this, can't able to create users as well.

**Comment by zegenie** [comment] 2021-12-28 08:29
This was caused by an error in the module initialization so it wasn't able to detect available encryption options. This has been fixed now.

**Closed by zegenie** 2021-12-28 08:29 UTC
