### ISSUE TITLE
Board problems

### ISSUE THREAD

**Issue by alecgm** [pachno/pachno#11] opened 2021-07-16 14:15 UTC
I do no get how boards actually are working. How do I see my issues or tasks in a board.  There's talk about the backlog containing my issues, but there's no backlog anywhere. Also it seems I cannot delete columns anymore or switch their position.

**Comment by hazhayder** [comment] 2021-07-31 17:39
Same problem with me. I installed one for me and I am lost how this is working

**Comment by zegenie** [comment] 2022-01-06 13:44
Because of the way boards work in that they will only show issues matching columns on the board within the search selected for the board, it may sometimes cause confusion. We're working on board improvements - including improvements to the backlog - which should hopefully fix these confusions.

**Comment by zegenie** [comment] 2022-01-17 17:20
Several big improvements to the board functionality is being implemented for the next release. Among these are more ways to prevent misconfiguration of boards, and some helpful pointers in cases where the board configuration prevents issues from being shown:
![image](https://user-images.githubusercontent.com/205936/149813232-988feaed-30e6-41e9-85c9-4ad9bff19b27.png)
![image](https://user-images.githubusercontent.com/205936/149813395-b965fa1c-3fbc-47ef-9e76-bf9ca48de912.png)

A new swimlane identifier that works with the configured epic issue type should also help reduce confusion:
![image](https://user-images.githubusercontent.com/205936/149813487-f7a8890d-b703-4f1a-b973-1e2070be23e8.png)

**Comment by superseby2** [comment] 2022-01-28 10:52
It might be interesting to re-open this issue.  I am still trying to get my head around how boards work .. 

What I tried to do 

- create a regular board of type "Generic"
- create a column "Todo" with filter set to New 
  -  First thing weird : there is no way to add anything from the column (no add button available)
  - I can click on "Report an issue" -> select type of task and click "File issue" -> the dialog box is not closing hence if I click more than once I will get duplicates
  - I need to refresh to see the tasks in the right column (Todo)
  - Note that there is no way for me to change the filter on the column
  - I then create a second column 
    - if i set the filter to Progress I won't be able to move my tasks from Todo to Progress (I guess that somewhere linked to a defined workflow, but I could not find a way to specify a workflow)
    - If I set the filter to Confirmed, I ll be able to move tasks but they will disappear once dropped into the Confirmed column. (need to refresh to see them)

All in all, the hardest part, to me, is to have specific workflow, I need is to create columns in a specific order and *that* should define my workflow.

Thx!

**Comment by zegenie** [comment] 2022-01-28 11:19
This makes total sense and is great feedback.

**Comment by zegenie** [comment] 2022-01-30 00:11
To address some of your feedback:
* The missing "add card" button was caused by a bug that should be fixed now
* The non-closing "Report issue popup" was caused by the same bug
* The non-appearing issue was also caused by the same bug
* Changing filters in the column will be added, but isn't possible at the moment

With that out of the way, the second part of your feedback is the most critical, as this hits the nail on the head with regards to what the main problem here was: the lack of connection or visual feedback that there was an invisible requirement to understand or know about the related workflow to move issues.

All boards will now have a setting that lets you specify how dragging cards should work:
![image](https://user-images.githubusercontent.com/205936/151681763-511eb023-56f6-4a6c-99a5-919b5ea762cf.png)

This setting will default to one of the relaxed settings, which will allow you to freely move issues between columns as you'd expect from the board. You can also choose to enforce the workflow when setting up the board, which is what the default setting is today.

This will be available in `master` soon. As `master` is a moving target for the next release, you may have to manually change the `installed` file to remove the line that says you've updated to version 1.0.5, and run the `upgrade` command again, as this requires a database column change.

**Comment by zegenie** [comment] 2022-02-01 12:11
Last night the board also got functionality to edit the columns on the board. This will be available in the 1.0.5 release later today and should properly close this issue.

![image](https://user-images.githubusercontent.com/205936/151966036-fc9a5403-d5e7-4fc4-86fa-7c70226acfa4.png)

Please feel free to post about reopening this issue again if the problems still persist.

**Closed by zegenie** 2022-02-01 12:11 UTC

**Comment by superseby2** [comment] 2022-02-03 15:49
Thx for all this!  Will test and report back.

**Comment by superseby2** [comment] 2022-02-03 16:20
A super quick feedback : it's way better! Good job!
Not quite sure yet where you adjust your workflow with your dashboard if you wanna have your cards respecting it?
Also the contrast on my computer is very bad. Looking at your screenshot, clearly it looks better on yours. 
Dunno what could be the problem? I have been building using the docker-compose.yml. Maybe am i missing a step regarding something css-related ?


![image](https://user-images.githubusercontent.com/32198925/152382992-c8e0a864-8365-4bf8-bafa-3a2ced4c24d1.png)

**Comment by superseby2** [comment] 2022-02-03 16:30
I think I managed to answer my question related to workflow-board relationship. In fact it is more Project-Workflow relationship if I am not mistaken. Everything gets crystal-clear when you find the project's settings ;)
